stages:
  data_collection:
    cmd: python src/data_collection.py
    deps:
    - src/data_collection.py
    - water_potability.csv
    params:
    - data_collection.test_size
    outs:
    - data/raw/train.csv
    - data/raw/test.csv

  pre-processing:
    cmd: python src/data_prep.py
    deps:
    - src/data_prep.py
    - data/raw/train.csv
    - data/raw/test.csv
    outs:
    - data/processed/train_processed.csv
    - data/processed/test_processed.csv
    
  model_building:
    cmd: python src/model_building.py
    deps:
    - src/model_building.py
    - data/processed/train_processed.csv
    params:
    - model_building.n_estimators
    outs:
    - models/model.pkl

  model_evaluation:
    cmd: python src/model_eval.py
    deps:
    - src/model_eval.py
    - data/processed/test_processed.csv
    - models/model.pkl
    outs:
    - reports/metrics.json